[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "morn"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.34", features = ["persistence"] }
egui = "0.34"
egui-wgpu = "0.34"
wgpu = "29.0"
engine = { path = "../engine" }
player-core = { path = "../player-core" }
render = { path = "../render" }
sync = { path = "../sync" }
media = { path = "../media" }
image = { version = "0.25", default-features = false, features = ["png"] }
