[package]
name = "engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
player-core = { path = "../player-core" }
media = { path = "../media" }
audio = { path = "../audio" }
sync = { path = "../sync" }
subtitle = { path = "../subtitle" }
persist = { path = "../persist" }
crossbeam-channel = { workspace = true }
ffmpeg-next = "8.1"
ringbuf = "0.5"
